name: Publish Snapshot
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Set snapshot version
        run: |
          CURRENT_VERSION=$(grep "^version" build.gradle.kts | cut -d'"' -f2)
          SNAPSHOT_VERSION="${CURRENT_VERSION}-SNAPSHOT"
          sed -i "s/version = \"$CURRENT_VERSION\"/version = \"$SNAPSHOT_VERSION\"/" build.gradle.kts
          echo "Publishing snapshot version: $SNAPSHOT_VERSION"
      
      - name: Build
        run: ./gradlew build -x jsTest -x jsBrowserTest
      
      - name: Publish Snapshot to Maven Central
        run: ./gradlew publishToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          # Snapshots don't require signing on Maven Central
      
      - name: Publish to GitHub Packages
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}